# Generated by Django 6.0.7 on 2026-08-14 16:01

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='picture',
            field=models.ImageField(upload_to=accounts.validators.avatar_upload_path_validator),
        ),
    ]
